# fly.toml app configuration file generated for jeheecheon-web on 2025-07-09T13:59:11Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jeheecheon-web'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 4001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
